#!/usr/bin/env python3
"""
Generate docs/SUPPORTED_DEVICES.md from the DEVICE_TYPES catalog and EEP_SPECIFICATIONS.

Run from the repository root:
    python scripts/generate_list_of_devices.py
"""

from pathlib import Path

from enocean_async.eep import EEP_SPECIFICATIONS
from enocean_async.eep.device_type import DEVICE_TYPES
from enocean_async.semantics.observable import Observable
from enocean_async.semantics.observers.button import CLICKED, HELD, PRESSED, RELEASED

_BUTTON_EVENT_VALUES = ", ".join(f"`{v}`" for v in [PRESSED, CLICKED, HELD, RELEASED])

OUT = Path(__file__).parent.parent / "docs" / "SUPPORTED_DEVICES.md"

generic = sorted(
    (dt for dt in DEVICE_TYPES if dt.manufacturer is None),
    key=lambda dt: (dt.eep.rorg, dt.eep.func, dt.eep.type),
)
specific = sorted(
    (dt for dt in DEVICE_TYPES if dt.manufacturer is not None),
    key=lambda dt: (dt.manufacturer.display_name, dt.model),  # type: ignore[union-attr]
)


def _entities_str(spec) -> str:
    if not spec.entities:
        return "—"

    # If every entity has the same single observable, annotate it once at the end
    obs_per_entity = [tuple(sorted(o.value for o in e.observables)) for e in spec.entities]
    all_same_single = len(set(obs_per_entity)) == 1 and len(obs_per_entity[0]) == 1

    ids_str = ", ".join(f"`{e.id}`" for e in spec.entities)

    if all_same_single:
        shared = obs_per_entity[0][0]
        if shared == Observable.BUTTON_EVENT.value:
            return f"{ids_str} (button_event: {_BUTTON_EVENT_VALUES})"
        # Self-descriptive channel names (e.g. ch1_switch_state) need no annotation
        return ids_str

    # Mixed or multi-observable: annotate per entity where observables aren't obvious
    parts = []
    for e in spec.entities:
        obs = sorted(o.value for o in e.observables)
        obs_suffix = f" ({', '.join(obs)})" if len(obs) > 1 else ""
        parts.append(f"`{e.id}`{obs_suffix}")
    return ", ".join(parts)


def _instr_str(spec) -> str:
    keys = list(spec.encoders.keys())
    return ", ".join(f"`{k.value}`" for k in keys) if keys else "—"


with OUT.open("w", encoding="utf-8") as f:
    f.write("# List of supported EnOcean devices\n")
    f.write("<!-- This file is auto-generated by scripts/generate_list_of_devices.py, do not edit manually. -->\n\n")

    f.write("## Manufacturer-specific entries\n\n")
    f.write("These entries represent known physical products.\n\n")
    f.write("| Manufacturer | Model | EEP | Description | Entities | Instructions |\n")
    f.write("|---|---|---|---|---|---|\n")
    for dt in specific:
        mfr = dt.manufacturer.display_name  # type: ignore[union-attr]
        spec = EEP_SPECIFICATIONS.get(dt.eep)
        entities = _entities_str(spec) if spec else "—"
        instr = _instr_str(spec) if spec else "—"
        f.write(f"| {mfr} | {dt.model} | {dt.eep} | {dt.description} | {entities} | {instr} |\n")

    f.write("\n## Generic EEP entries\n\n")
    f.write("These entries cover any device implementing the given EEP.\n\n")
    f.write("| EEP | Description | Entities | Instructions |\n")
    f.write("|---|---|---|---|\n")
    for dt in generic:
        spec = EEP_SPECIFICATIONS.get(dt.eep)
        entities = _entities_str(spec) if spec else "—"
        instr = _instr_str(spec) if spec else "—"
        f.write(f"| {dt.eep} | {dt.model} | {entities} | {instr} |\n")

print(f"Written {OUT.relative_to(Path.cwd())}")
