from .id import EEPID
from .profile import EEP, EEPDataField, EEPTelegram

EEP_DATABASE: dict[EEPID, EEP] = {
    EEPID.from_string("A5-07-03"): EEP(
        id=EEPID.from_string("A5-07-03"),
        name="Occupancy with Supply voltage monitor and 10-bit illumination measurement",
        cmd_size=0,
        cmd_offset=None,
        telegrams={
            0: EEPTelegram(
                name=None,
                datafields=[
                    EEPDataField(
                        id="SVC",
                        name="Supply voltage)",
                        offset=0,
                        size=8,
                        range_min=0,
                        range_max=250,
                        scale_min=0.0,
                        scale_max=5.0,
                        range_enum=None,
                        unit="V",
                    ),
                    EEPDataField(
                        id="ILL",
                        name="Illumination (linear)",
                        offset=8,
                        size=10,
                        range_min=0,
                        range_max=1000,
                        scale_min=0.0,
                        scale_max=1000.0,
                        range_enum=None,
                        unit="lx",
                    ),
                    EEPDataField(
                        id="PIR",
                        name="PIR Status",
                        offset=24,
                        size=1,
                        range_min=0,
                        range_max=1,
                        scale_min=0.0,
                        scale_max=0.0,
                        range_enum={
                            0: "Uncertain of occupancy status",
                            1: "Motion detected",
                        },
                        unit="",
                    ),
                ],
            )
        },
    ),
    EEPID.from_string("F6-02-01"): EEP(
        id=EEPID.from_string("F6-02-01"),
        name="Light and Blind Control - Application Style 1",
        cmd_size=0,
        cmd_offset=None,
        telegrams={
            0: EEPTelegram(
                name=None,
                datafields=[
                    EEPDataField(
                        id="R1",
                        name="Rocker 1st action",
                        offset=0,
                        size=3,
                        range_min=0,
                        range_max=7,
                        range_enum={
                            0: "Button A1",
                            1: "Button A0",
                            2: "Button B1",
                            3: "Button B0",
                        },
                    ),
                    EEPDataField(
                        id="EB",
                        name="Energy bow",
                        offset=3,
                        size=1,
                        range_min=0,
                        range_max=1,
                        range_enum={0: "released", 1: "pressed"},
                    ),
                    EEPDataField(
                        id="R2",
                        name="Rocker 2nd action",
                        offset=4,
                        size=3,
                        range_min=0,
                        range_max=7,
                        range_enum={
                            0: "Button A1",
                            1: "Button A0",
                            2: "Button B1",
                            3: "Button B0",
                        },
                    ),
                    EEPDataField(
                        id="SA",
                        name="2nd action",
                        offset=7,
                        size=1,
                        range_min=0,
                        range_max=1,
                        range_enum={0: "No 2nd action", 1: "2nd action valid"},
                    ),
                ],
            )
        },
    ),
    EEPID.from_string("D2-05-00"): EEP(
        id=EEPID.from_string("D2-05-00"),
        name="Blinds Control for Position and Angle, Type 0x00",
        cmd_size=4,
        cmd_offset=-4,
        telegrams={
            1: EEPTelegram(
                name="Go to Position and Angle",
                datafields=[
                    EEPDataField(
                        id="POS",
                        name="Vertical position",
                        offset=1,
                        size=7,
                        range_min=0,
                        range_max=127,
                        unit="",
                    ),
                    EEPDataField(
                        id="ANG",
                        name="Rotation angle",
                        offset=9,
                        size=7,
                        range_min=0,
                        range_max=127,
                        unit="",
                    ),
                    EEPDataField(
                        id="REPO",
                        name="Repositioning mode",
                        offset=17,
                        size=3,
                        range_min=0,
                        range_max=7,
                        range_enum={
                            0: "Directly to target POS/ANG",
                            1: "Up, then to target POS/ANG",
                            2: "Down, then to target POS/ANG",
                            3: "Reserved",
                            4: "Reserved",
                            5: "Reserved",
                            6: "Reserved",
                            7: "Reserved",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="LOCK",
                        name="Set locking mode",
                        offset=21,
                        size=3,
                        range_min=0,
                        range_max=7,
                        range_enum={
                            0: "No change",
                            1: "Set blockage mode",
                            2: "Set alarm mode",
                            3: "Reserved",
                            4: "Reserved",
                            5: "Reserved",
                            6: "Reserved",
                            7: "Unblock",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="CHN",
                        name="Channel",
                        offset=24,
                        size=4,
                        range_min=0,
                        range_max=15,
                        range_enum={
                            0: "Channel 1",
                            1: "Channel 2",
                            2: "Channel 3",
                            3: "Channel 4",
                            15: "All channels",
                        },
                        unit="",
                    ),
                ],
            ),
            2: EEPTelegram(
                name="Stop",
                datafields=[
                    EEPDataField(
                        id="CHN",
                        name="Channel",
                        offset=0,
                        size=4,
                        range_min=0,
                        range_max=15,
                        range_enum={
                            0: "Channel 1",
                            1: "Channel 2",
                            2: "Channel 3",
                            3: "Channel 4",
                            15: "All channels",
                        },
                        unit="",
                    ),
                ],
            ),
            3: EEPTelegram(
                name="Query Position and Angle",
                datafields=[
                    EEPDataField(
                        id="CHN",
                        name="Channel",
                        offset=0,
                        size=4,
                        range_min=0,
                        range_max=15,
                        range_enum={
                            0: "Channel 1",
                            1: "Channel 2",
                            2: "Channel 3",
                            3: "Channel 4",
                            15: "All channels",
                        },
                        unit="",
                    ),
                ],
            ),
            4: EEPTelegram(
                name="Reply Position and Angle",
                datafields=[
                    EEPDataField(
                        id="POS",
                        name="Vertical position",
                        offset=1,
                        size=7,
                        range_min=0,
                        range_max=127,
                        unit="",
                    ),
                    EEPDataField(
                        id="ANG",
                        name="Rotation angle",
                        offset=9,
                        size=7,
                        range_min=0,
                        range_max=127,
                        unit="",
                    ),
                    EEPDataField(
                        id="LOCK",
                        name="Locking modes",
                        offset=21,
                        size=3,
                        range_min=0,
                        range_max=7,
                        range_enum={
                            0: "Normal (no lock)",
                            1: "Blockage mode",
                            2: "Alarm mode",
                            3: "Reserved",
                            4: "Reserved",
                            5: "Reserved",
                            6: "Reserved",
                            7: "Reserved",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="CHN",
                        name="Channel",
                        offset=24,
                        size=4,
                        range_min=0,
                        range_max=3,
                        range_enum={
                            0: "Channel 1",
                            1: "Channel 2",
                            2: "Channel 3",
                            3: "Channel 4",
                        },
                        unit="",
                    ),
                ],
            ),
        },
    ),
    EEPID.from_string("D2-20-02"): EEP(
        id=EEPID.from_string("D2-20-02"),
        name="Fan Control, Type 0x02",
        cmd_size=7,
        cmd_offset=1,
        telegrams={
            0: EEPTelegram(
                name="Fan Control Message",
                datafields=[
                    EEPDataField(
                        id="RSR",
                        name="Room size reference",
                        offset=10,
                        size=2,
                        range_min=0,
                        range_max=3,
                        range_enum={
                            0: "Used",
                            1: "Not used",
                            2: "Default",
                            3: "No change",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="RS",
                        name="Room size",
                        offset=12,
                        size=4,
                        range_min=0,
                        range_max=15,
                        range_enum={
                            0: "< 25m²",
                            1: "25m² - 50m²",
                            2: "50m² - 75m²",
                            3: "75m² - 100m²",
                            4: "100m² - 125m²",
                            5: "125m² - 150m²",
                            6: "150m² - 175m²",
                            7: "175m² - 200m²",
                            8: "200m² - 225m²",
                            9: "225m² - 250m²",
                            10: "250m² - 275m²",
                            11: "275m² - 300m²",
                            12: "300m² - 325m²",
                            13: "325m² - 350m²",
                            14: ">350m²",
                            15: "No change",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="FS",
                        name="Fan speed",
                        offset=24,
                        size=8,
                        range_min=0,
                        range_max=255,
                        range_enum={
                            **{i: f"{i}%" for i in range(101)},
                            **{i: "Reserved" for i in range(101, 253)},
                            253: "Auto",
                            254: "Default",
                            255: "No change",
                        },
                        unit="",
                    ),
                ],
            ),
            1: EEPTelegram(
                name="Fan Status Message",
                datafields=[
                    EEPDataField(
                        id="HCS",
                        name="Humidity control status",
                        offset=8,
                        size=2,
                        range_min=0,
                        range_max=3,
                        range_enum={
                            0: "Disabled",
                            1: "Enabled",
                            2: "Reserved",
                            3: "Not supported",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="RS",
                        name="Room size",
                        offset=12,
                        size=4,
                        range_min=0,
                        range_max=15,
                        range_enum={
                            0: "< 25m²",
                            1: "25m² - 50m²",
                            2: "50m² - 75m²",
                            3: "75m² - 100m²",
                            4: "100m² - 125m²",
                            5: "125m² - 150m²",
                            6: "150m² - 175m²",
                            7: "175m² - 200m²",
                            8: "200m² - 225m²",
                            9: "225m² - 250m²",
                            10: "250m² - 275m²",
                            11: "275m² - 300m²",
                            12: "300m² - 325m²",
                            13: "325m² - 350m²",
                            14: ">350m²",
                            15: "No change",
                        },
                        unit="",
                    ),
                    EEPDataField(
                        id="FS",
                        name="Fan speed",
                        offset=24,
                        size=8,
                        range_min=0,
                        range_max=255,
                        range_enum={
                            **{i: f"{i}%" for i in range(101)},
                            **{i: "Reserved" for i in range(101, 253)},
                            253: "Auto",
                            254: "Default",
                            255: "No change",
                        },
                        unit="",
                    ),
                ],
            ),
        },
    ),
}
"""A simple in-memory database of supported EEP profiles. For performance reasons, this is implemented as a dictionary mapping EEPID to EEP."""
